version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    networks:
      - tutorial
  redis:
    image: redis:7
    environment:
      - REDIS_PASSWORD=root
    ports:
      - "6379:6379"
  test-db:
    image: postgres:15
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    networks:
      - tutorial
networks:
  tutorial:
